### ISSUE TITLE
{"Required property 'thumb' not found in JSON. Path 'result[2].message.document', line 4, position 443."}

### ISSUE THREAD

**Issue by NaderStar** [MrRoundRobin/telegram.bot#13]
hi there, it happens when someone send a document like pdf to the bot

**Comment by LuckyPed** [comment]
Yeh, 3 error happened like this , mostly relating to the thumb , i think its a problem duo to their own API system documentation, 
either how,
I fixed them by changing the Required Property to not Required !  write default instead of Always and it will fix !

Check my first issue : 
https://github.com/MrRoundRobin/telegram.bot/issues/5

**Comment by MrRoundRobin** [comment]
this should be resolved since the last API updates and 05cbcc846e1220b851930a42682f51b5954d1b1a. Can you confirm?

**Comment by NaderStar** [comment]
tnx got it
