### ISSUE TITLE
Recieve() should not Return

### ISSUE THREAD

**Issue by eaba** [MrRoundRobin/telegram.bot#142]
Hello @MrRoundRobin 
```
private async void Receive()
        {
            while (IsReceiving)
            {
                var timeout = Convert.ToInt32(PollingTimeout.TotalSeconds);

                var updates = await GetUpdates(MessageOffset, timeout: timeout).ConfigureAwait(false);

                foreach (var update in updates)
                {
                    OnUpdateReceived(new UpdateEventArgs(update));
                    MessageOffset = update.Id + 1;
                }
            }
        }
```
Should never return while IsRecieving is `true`
`async` could be the cause!
Please add `Thread.Sleep(100)` to prevent "cpu intensive loop"!

**Comment by eaba** [comment]
And also kindly update the nuget package too!

**Comment by MrRoundRobin** [comment]
why should `Receive()` not return?

`async void` is "for methods that perform activities that can be categorized as 'fire and forget.'" [source](https://msdn.microsoft.com/en-us/library/hh524395.aspx#BKMK_VoidReturnType). Because the received updates are forwarded as events this is what i want. Reviewing this I decided to add an error event.

As the `GetUpdates` uses [long pooling](https://en.wikipedia.org/wiki/Push_technology#Long_Polling) this should not be a "cpu intensive loop", maybe I'll add an option or parameter "StopOnError".

I'm working on an CI NuGet Feed, not finished yet.

**Comment by eaba** [comment]
There is no difference between GetUpdates and StartRecieving then!
StartRecieving has to keep running for as long as IsRecieving is true.

Leaving that way, I feel, defeats the purpose of having there!
With the current implementation StartRecieving has to be called continuously like GetUpdates!
Having a while loop means it should be kept alive as long as possible!

I hope you understand what i meant?

**Comment by MrRoundRobin** [comment]
`Receive` returns immediately and runs in background

**Comment by eaba** [comment]
Okay!
While it is running can request be made at the same time?

**Comment by MrRoundRobin** [comment]
of course

**Comment by eaba** [comment]
Thats what i wanted to find out!
Thanks
