### ISSUE TITLE
How to validate if a username is registered in telegram? 

### ISSUE THREAD

**Issue by samanatabaki** [MrRoundRobin/telegram.bot#169]
Hello,

As you see in the title I want to find if a specific username (bot name, channel name, etc) is registered in telegram database. It is crucial for me, because I would love to know if a channel is really existed then do something else. 

And also I would love to know if my bot (for example: mytestbot) is in a channel as that channel's admin user? For this first I should validate channel existence (my first question here) and then validate my bot as admin in that specific channel.

I'm waiting for your kind guidance :-)

**Comment by MrRoundRobin** [comment]
In general, first take a look at the [official API Docs](https://core.telegram.org/bots/api) and see if there is an method for this. If there is, but you can't find it in the library, create an issue. 

i created an example which cheks if a a public supergroup or channel exits, you can extend it with [`GetChatAdministrators`](https://mrroundrobin.github.io/telegram.bot/html/Overload_Telegram_Bot_TelegramBotClient_GetChatAdministratorsAsync.htm)

```c#

// event Bot.MessageReceived
var message = messageEventArgs.Message;
// or GetUpdates()
var message = update.Message;

var args = message.Text.Split(' ');

if (args.Length != 2)
{
    await
        Bot.SendTextMessageAsync(message.Chat.Id, "usage: `/c <channelname>`",
            parseMode: ParseMode.Markdown);
    return;
}

await Bot.SendChatActionAsync(message.Chat.Id, ChatAction.Typing);

var channel = args[1];

try
{
    var count = await Bot.GetChatMembersCountAsync(channel);

    await
        Bot.SendTextMessageAsync(message.Chat.Id, $"The channel or group `{channel}` has `{count}` members",
            parseMode: ParseMode.Markdown);
}
catch (ApiRequestException e) when (e.Message.Contains("not found"))
{
    await Bot.SendTextMessageAsync(message.Chat.Id, $"The channel or group `{channel}` does not exist or is private",
        parseMode: ParseMode.Markdown);
}

```

**Comment by samanatabaki** [comment]
It worked when I used myBot.GetChatMembersCountAsync(channelName); ! thank you
but when I use this statement

var admins = await myBot.GetChatAdministratorsAsync(channelName);

this is the exception I get:

Bad Request: Channel members are unavailable

**Comment by MrRoundRobin** [comment]
i get `Bad Request: Channel members are unavailable` if i request the admins from a chennel which the bot itself is no admin, this is inteded

**Comment by Darvin09** [comment]
How validate wether telegram user id is valid or not in python

**Comment by bennettceo** [comment]
I understand that the last answer was posted 5 years ago, but since the topic may still be relevant, i'd like to add that the cleanest way i've found to check if username is registered is by using the Fragment.com API (through an unofficial wrapper or by writing your own). 
However, Fragment only allows checking usernames belonging to user accounts. If a username belongs to a channel or etc., the request returns an error - the same as it does for a non-existent account.

**Comment by wiz0u** [comment]
Another solution is to use WTelegramBot which is 100% compatible with Telegram.Bot but offers some advanced bot features thanks to using Client API (for bots) instead of Bot API.
One of these features is to resolve (get information) on any username via GetChat(username).
See https://www.nuget.org/packages/WTelegramBot#readme-body-tab
