### ISSUE TITLE
does it work on mono?

### ISSUE THREAD

**Issue by Radzhab** [MrRoundRobin/telegram.bot#17]
I want use it with nancyfx. Its work on ubuntu with mono?

**Comment by MrRoundRobin** [comment]
can you try?

**Comment by Neftedollar** [comment]
Hi, I've just compile and run simple app that use this library (installed from nuget) with mono 4.0.1 (Windows 10).

**Comment by marcovannoord** [comment]
I think something changed with the telegram certificates, since even after adding the certificates (with mozroots). I still get the authentication error; which would suggest i don't have the necessary certificates. 
I've tried this with the "helloworld" from the api; Raspbian Jessie with Mono 4.0.1. Could someone confirm this?
