### ISSUE TITLE
Unexpected ForceReply markup behavior in group chat

### ISSUE THREAD

**Issue by a-a-k** [MrRoundRobin/telegram.bot#251]
### Steps to reproduce

Sending message in private chat works ok. Sending equal message in group not works as expected.
```
public static ReplyMarkup ForceReply { get; } = new ForceReply
   {
        Force = true,
        Selective = true
   }

public static async Task BeginSendingAction(TelegramBotClient bot, Message message)
   {
        await bot.SendChatActionAsync(message.Chat.Id, ChatAction.Typing);
        await bot.SendTextMessageAsync(message.Chat.Id, "_Type your message_", true, false, message.MessageId, Keyboards.ForceReply, ParseMode.Markdown);
   }

public static async Task BeginSendingAction(TelegramBotClient bot, CallbackQuery callbackQuery)
    {
        await bot.SendChatActionAsync(callbackQuery.Message.Chat.Id, ChatAction.Typing);
        await bot.SendTextMessageAsync(callbackQuery.Message.Chat.Id, "_Type your message_", true, false, callbackQuery.Message.MessageId, Keyboards.ForceReply, ParseMode.Markdown);
    }
```
### Expected  behavior

Expected force replied message from bot in all chats.

### Actual behavior

Message from bot replied in private chat only.

### Environment data

*NuGet Package Version:* (11.0.0 beta 4)

*.NET Version:* (4.6)

*IDE:* (VS2015)

*App:* (Desktop,  Android)

**Comment by mhverbakel** [comment]
Dear a-a-k,

I might be misunderstanding your question, but I think this might be an issue where you assume something different than the Bot API. Please contact https://telegram.me/BotSupport, they will probably be able to help you with your problem.

If the problem is not caused by the library, please close this issue, otherwise clarify how this problem comes from the library.

Kind regards,
Martijn Verbakel

**Comment by a-a-k** [comment]
It solved by set for the `Selective` property `false` value.
