### ISSUE TITLE
How to creat project with this lib?

### ISSUE THREAD

**Issue by Sammers21** [MrRoundRobin/telegram.bot#92]
How to create a project and specify a link to this library?Help please i m nee yours instructions

**Comment by guitarxhero** [comment]
Under Visual Studio, I recommend using the NuGet package manager since the latest version is `v8.0.0`.

Make sure to have your project opened. To install the Telegram.Bot package, go under Tools | NuGet Package Manager | Package Manager Console.

Then, copy paste this line: `Install-Package Telegram.Bot`, the package manager will automatically make the references into your project.

Hope this helped you.
